### ISSUE TITLE
How to pass post id

### ISSUE THREAD

**Issue by diliphirapara95** [rumansaleem/php-mvc-demo#1]
I appreciate the code you've pushed on MVC, I just configured the project and it is running correctly, The only thing is How Can I make the URL dynamic?

URL/post/10
URL/post/11
URL/post/12

I want to pass as this above URL, I know I need to do it manually, but did you created this flow? if you created can you push it?

**Comment by rumansaleem** [comment]
No, I didn't configure this one. The purpose of this repo was to demonstrate the MVC using core php, for simplicity it was kept as simple as possible.

But, if you want you can make a PR. 😉
